name: Stock Checker

on:
  schedule:
    - cron: "*/15 * * * *"   # 15 dakikada bir
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_API: ${{ secrets.BOT_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
